### ISSUE TITLE
An extra widget on the end of the tab list

### ISSUE THREAD

**Issue by visign3d** [alihaider78222/dynamic_tabbar#1]
Is it a way to add an extra Widget , like add button on the end of the tablist?
|Tab1|Tab2|Tab3|+|

**Comment by alihaider78222** [comment]
Currently, there are no options for `Leading` and `Trailing` widgets within the tabs. However, I appreciate your suggestion, and I'll make sure to include these features in an upcoming release. 🙌

**Comment by alihaider78222** [comment]
`Leading` and `Trailing` Widget parameters are added in the new version 🎉

**Comment by alihaider78222** [comment]
`Leading` and `Trailing` Widget parameters are added in the new version 🎉
