### ISSUE TITLE
Tab not changed after press or swipe to another tab 

### ISSUE THREAD

**Issue by u-sour** [alihaider78222/dynamic_tabbar#17]
Hi, after I update to v 1.0.8, when I press or swipe to another tab, it doesn't change and doesn't get any error. I already checked my code. It is the same. I haven't changed any line. 
**Note:** On v 1.0.7 it works.

https://github.com/user-attachments/assets/4fe17dca-b8e1-4fcb-b9c9-f9eff4400a0c

**Comment by deakjahn** [comment]
@u-sour By looking into the code, this is the same problem: https://github.com/alihaider78222/dynamic_tabbar/issues/18

It doesn't actually stay but it gets reset to the first tab. Which happens to be the same in your case. :-)

**Comment by u-sour** [comment]
@deakjahn nvm, i decide to stop use this package and use default flutter tabbar.

**Comment by deakjahn** [comment]
It's up to you, of course. I simply changed those two lines and I suppose our package author will simply fix it and revert the regression soon. Apart from this small error, I found the package to be very good and useful for my purposes as I also need dynamic tabs.

**Comment by alihaider78222** [comment]
@u-sour,

please update to the latest version of [dynamic_tabbar](https://pub.dev/packages/dynamic_tabbar) (v1.0.9), 
hope this fix (contributed by @deakjahn ) will resolve this issue.

**Comment by u-sour** [comment]
@alihaider78222 Thank you, I close this issue.
