### ISSUE TITLE
TabController gets recreated with index 0

### ISSUE THREAD

**Issue by deakjahn** [alihaider78222/dynamic_tabbar#18]
See the following two lines:

https://github.com/alihaider78222/dynamic_tabbar/blob/d000fdb756015fda9a87fbae911cbee5c54a541c/lib/dynamic_tabbar.dart#L192

and

https://github.com/alihaider78222/dynamic_tabbar/blob/d000fdb756015fda9a87fbae911cbee5c54a541c/lib/dynamic_tabbar.dart#L227

First, you shouldn't require `onTabControllerUpdated()`, if it's null, simply don't call it. But even more important than that: if you call it, don't recreate the tab controller here. This is something that I could only experience if the page I'm on changes something else in the state and Flutter recreates it. In this case, it always returns to the first tab upon state change because the `getTabController()` call resets the index.

Replacing both lines with

```
if (_tabController != null) widget.onTabControllerUpdated?.call(_tabController!);
```

seems to work all right for me.

**Comment by alihaider78222** [comment]
Hi @deakjahn,

This fix has been added to the latest version of [dynamic_tabbar](https://pub.dev/packages/dynamic_tabbar) (v1.0.9).
and please feel free to create a Pull request for any improvements or bug fixes in the package.

Thanks 🙌
