### ISSUE TITLE
Feature (ScrollPhysics)

### ISSUE THREAD

**Issue by rodolfogoulart** [alihaider78222/dynamic_tabbar#3]
Can you add a parameter tabBarPhysics to set on TabBarView
ScrollPhysics? physics,

``` Dart
Expanded(
              child: TabBarView(
                physics: widget.tabBarPhysics
                controller: _tabController,
                children: widget.dynamicTabs.map((tab) => tab.content).toList(),
              ),
            ),

```

My case i need to have NeverScrollableScrollPhysics() on TabBarView

**Comment by alihaider78222** [comment]
Hi @rodolfogoulart,
Thanks for pointing out the missing parameters, your pull request has been merged and the latest version 1.0.6 is now published and available on [pub.dev](https://pub.dev/packages/dynamic_tabbar) :)
