### ISSUE TITLE
Tab positioning per parameter

### ISSUE THREAD

**Issue by fumelotta** [alihaider78222/dynamic_tabbar#8]
Right now it can be steered "onAddTabMoveTo: MoveToTab.last" only to last tab or stay. In my case I have the first tab where data must be entered. If all are ok and saved some more tabs are added. Now I want the user to guide to tab 2 and not to last or stay. So something like MoveToNextTab or so.

Further more it would be good to have a function to position to any tab. So in above case - lets assume user did the input in tab 2 then system should guide him to tab 3. Here the user can decide to enter data or go directly to tab 4 or 5 (which are alreay added)

**Comment by alihaider78222** [comment]
Hi @fumelotta,

More `MoveToTab` enums are added in the latest version of [dynamic_tabbar](https://pub.dev/packages/dynamic_tabbar) (v1.0.8).
and in addition `onAddTabMoveToIndex` attribute is also added to move to specific index if needed, it overrides the default `onAddTabMoveTo`, so use it carefully.

Thanks

**Comment by fumelotta** [comment]
Thanks
